version: '3'
services:
  api:
    container_name: api
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - '7777:7777'
    depends_on:
      - postgresdb
    networks:
      - api-network

  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
    networks:
      - api-network

volumes:
  db:
networks:
  api-network:
